version: "3.8"

services:
  app:
    image: car-dealer-admin
    ports:
      - "3333:3333"
    env_file:
      - .env.docker
  database:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
