version: "3.8"

services:
  app:
    image: car-dealer
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database
    env_file:
      - .env.docker
  database:
    image: postgres:14.2
    restart: always
    env_file:
      - .env.docker
    ports:
      - 5432:5432
